### ISSUE TITLE
ERROR:  There was an error getting the token in openvidu-call

### ISSUE THREAD

**Issue by abhijithb92** [OpenVidu/openvidu-call#45]
Here is the error.
`ERROR:  There was an error getting the token: 504 Http failure response for https://<PUBLIC_IP>`/call: 504 Gateway Time-out`

What is this "/call" path the request is attempting to reach?

**Comment by abhijithb92** [comment]
It was some issue with the way I configured openvidu-server. I got the UI running after I used a different server that is properly configured.

**Comment by in-fke** [comment]
I have the same issue with 2.20.0

nginx container default.conf says
```
    # Your App
    location / {
        proxy_pass http://yourapp; # Openvidu call by default
    }
```

```
# Your App
upstream yourapp {
    server localhost:5442;
}
```
checking where this is leading to:
```
insvkn69:/opt/openvidu # lsof -i :5442
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
node    16468 root   19u  IPv6 351721546      0t0  TCP *:5442 (LISTEN)
```

yet

```
16291 ?        Sl     0:00  |   \_ docker-containerd-shim -namespace moby -workdir /opt2/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/4e3073f60e972c4919b4b75dcdf567cf3840a3b0fe4
6b514967169207517d5ac -address /var/run/docker/containerd/docker-containerd.sock -containerd-binary /usr/sbin/containerd -runtime-root /var/run/docker/runtime-runc
16318 ?        Ss     0:00  |       \_ /bin/sh /usr/local/bin/entrypoint.sh
16361 ?        Sl     0:00  |           \_ node /usr/local/bin/nodemon openvidu-call-server.js
16468 ?        Sl     0:00  |               \_ /usr/local/bin/node openvidu-call-server.js
```
this comes from docker-compose.override.yml
```
    # --------------------------------------------------------------
    app:
        image: openvidu/openvidu-call:2.20.0
        restart: on-failure
        network_mode: host
        environment:
            - SERVER_PORT=5442
            - OPENVIDU_URL=http://localhost:5443
            - OPENVIDU_SECRET=${OPENVIDU_SECRET}
            - CALL_OPENVIDU_CERTTYPE=${CERTIFICATE_TYPE}
        logging:
            options:
                max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
```

I couldn't tell anything wrong up to here, just that "/call" is running into 504

Tried to revert to 2.12.0 yield in the result, that 2.12.0 is not listening to 5442, does not seem to be running at all
docker logs for 2.12.0
```
OPENVIDU URL: http://localhost:5443
OPENVIDU SECRET: MY_SECRET
Restarting nginx: nginx.
```

Then I realized: openvidu-call's nodejs was ignoring NO_PROXY and thus tried to call openvidu-server's `/openvidu/api/sessions` via Proxy, which failed.
**I think this failure resulted in /call not returning.**

Workaround in override.yml
```
            - HTTP_PROXY=
            - HTTPS_PROXY=
            - http_proxy=
            - https_proxy=
```
and then '/call' worked.
